# permissions for end users to view personservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: personservice-viewer-role
rules:
- apiGroups:
  - charts.wanja.org
  resources:
  - personservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.wanja.org
  resources:
  - personservices/status
  verbs:
  - get
