postgresql:
    auth:
        username: wanja
        password: wanja
        database: wanjadb

    primary:
        podSecurityContext:
            enabled: false
            fsGroup: ""
        containerSecurityContext:
            enabled: false
            runAsUser: "auto"

    readReplicas:
        podSecurityContext:
            enabled: false
            fsGroup: ""
        containerSecurityContext:
            enabled: false
            runAsUser: "auto"

    volumePermissions:
        enabled: false
        securityContext:
            runAsUser: "auto"

deployment:
    image: quay.io/wpernath/person-service
    version: v1.8.9-native
    replicas: 1
    includeHealthChecks: false

config:
    greeting: 'Hello from chart with subchart'

