namePrefix: staging-  

commonLabels:
  variant: staging

commonAnnotations:
  note: We are on staging now
  stage: staging

bases:
- ../../base

patchesStrategicMerge:
  - deployment.yaml
  - route.yaml