apiVersion: batch/v1
kind: Job
metadata:
    name: "{{ .Release.Name }}-job"
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Chart.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    annotations:
        # This is what defines this resource as a hook. Without this line, the
        # job is considered part of the release.
        "helm.sh/hook": post-install,post-upgrade
        "helm.sh/hook-weight": "-5"
        "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
    ttlSecondsAfterFinished: 60
    template:
        metadata:
            name: {{ .Chart.Name }}
            labels:
                "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
        spec:
            restartPolicy: Never
            containers:
            - name: post-install-job
              image: "registry.access.redhat.com/ubi8/ubi-minimal:latest"              
              command: 
              - /bin/sh
              - -c 
              - |
                echo "WELCOME TO '{{ .Chart.Name }}-{{ .Chart.Version }}' "
                echo "-------------------------------------------------"
                echo "Here we could now do initialization work."
                echo "Like filling our DB with some data or what's so ever"
                echo "..."

                sleep 10


